import { useEffect, useState } from "react";
import { collection, deleteDoc, doc, getDocs } from "firebase/firestore";
import { db } from "./firebase";

function SavedSchemes({ user, onBack }) {
  const [savedSchemes, setSavedSchemes] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let active = true; getDocs(collection(db, "users", user.uid, "savedSchemes")).then((snapshot) => { if (active) { setSavedSchemes(snapshot.docs.map((savedDocument) => ({ id: savedDocument.id, ...savedDocument.data() }))); setLoading(false); } }).catch(() => { if (active) { setError("Saved schemes could not be loaded."); setLoading(false); } }); return () => { active = false; }; }, [user.uid]);
  async function removeScheme(schemeId) { try { await deleteDoc(doc(db, "users", user.uid, "savedSchemes", schemeId)); setSavedSchemes((current) => current.filter((scheme) => scheme.id !== schemeId)); } catch (removeError) { setError("The scheme could not be removed."); } }
  return <main><section className="ss-container ss-section ss-saved-page"><div className="ss-section-head"><div><button type="button" className="ss-back-link" onClick={onBack} data-testid="button-back-to-matcher">← Back to matching</button><span className="ss-eyebrow"><span className="ss-eyebrow-dot" /> Your little library</span><h1 className="ss-section-title">Saved for when<br />you’re ready.</h1></div><p className="ss-section-description">Keep promising support in one calm place. Come back whenever you want to take the next step.</p></div>{loading && <div className="ss-form-card"><div className="ss-skeleton" /></div>}{error && <div className="ss-alert error">!</div>}{!loading && !error && savedSchemes.length === 0 && <div className="ss-empty"><div className="ss-empty-icon">♡</div><h3>Nothing saved yet</h3><p>When a scheme feels useful, tap the heart. It will be waiting here for you.</p><button type="button" className="ss-pill-button primary" onClick={onBack} data-testid="button-empty-find-schemes">Find schemes →</button></div>}{!loading && !error && savedSchemes.length > 0 && <div className="ss-scheme-grid">{savedSchemes.map((scheme) => <article className="ss-scheme-card" key={scheme.id} data-testid={"card-saved-scheme-" + scheme.id}><div className="ss-scheme-topline"><h3 className="ss-scheme-name">{scheme.name}</h3><span className="ss-save saved">♥</span></div><p className="ss-scheme-benefit">{scheme.benefit}</p><div className="ss-saved-detail"><strong>Saved to your account</strong><span>Keep this scheme close while you prepare.</span></div><div className="ss-card-actions"><a className="ss-pill-button ghost" href={scheme.link} target="_blank" rel="noreferrer">Official site ↗</a><button type="button" className="ss-pill-button warm" onClick={() => removeScheme(scheme.id)} data-testid={"button-remove-scheme-" + scheme.id}>Remove</button></div></article>)}</div>}</section><footer className="ss-container ss-footer"><span>SchemeSathi · a clearer path to support</span><span>India-wide catalogue, thoughtfully simplified</span></footer></main>;
}
export default SavedSchemes;
